// --- File: backend/src/shipping/shipping.dto.ts ---
import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsNumber, IsObject, IsOptional, IsString, MinLength, ValidateNested } from 'class-validator';

export class SetActiveDto {
	@IsBoolean()
	isActive: boolean;
}

export class SetProviderCredentialsDto {
	@IsObject()
	credentials: {
		apiKey?: string;

		// optional (not required in current integration)
		accountId?: string;

		// webhook security (optional but recommended)
		webhookHeaderName?: string; // default "Authorization"
		webhookSecret?: string;     // generated by backend if missing
	};
}

export class CreateShipmentDto {
	@IsOptional()
	@IsString()
	notes?: string;

	@IsOptional()
	weightKg?: number;

	@IsOptional()
	@IsString()
	size?: 'Small' | 'Medium' | 'Large';
}

export class AssignOrderDto extends CreateShipmentDto { }

export class BulkAssignItemDto extends CreateShipmentDto {
	@IsNumber()
	orderId: number;
}

export class BulkAssignOrderDto {
	@IsArray()
	@ValidateNested({ each: true })
	@Type(() => BulkAssignItemDto)
	items: BulkAssignItemDto[];
}