// --- File: backend/src/shipping/shipping.dto.ts ---
import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsEnum, IsNumber, IsObject, IsOptional, IsString, MinLength, ValidateNested } from 'class-validator';

export class SetActiveDto {
	@IsBoolean()
	isActive: boolean;
}

export class SetProviderCredentialsDto {
	@IsObject()
	credentials: {
		apiKey?: string;

		// optional (not required in current integration)
		accountId?: string;

		// webhook security (optional but recommended)
		webhookHeaderName?: string; // default "Authorization"
		webhookSecret?: string;     // generated by backend if missing
	};
}

export class CreateShipmentDto {
	@IsOptional()
	@IsString()
	notes?: string;

	@IsOptional()
	weightKg?: number;

	@IsOptional()
	@IsString()
	size?: 'Small' | 'Medium' | 'Large';
}

export class AssignOrderDto extends CreateShipmentDto { }

export class BulkAssignItemDto extends CreateShipmentDto {
	@IsString()
	orderId: string;
}

export class BulkAssignOrderDto {
	@IsArray()
	@ValidateNested({ each: true })
	@Type(() => BulkAssignItemDto)
	items: BulkAssignItemDto[];
}

export class PrintMassAWBDto {
	@IsArray()
	@IsString({ each: true })
	orderIds: string[];

	@IsOptional()
	@IsEnum(['A4', 'A6'])
	requestedAwbType?: 'A4' | 'A6' = 'A4';

	@IsOptional()
	@IsEnum(['ar', 'en'])
	lang?: 'ar' | 'en' = 'ar';
}