export const citiesData = [
	{ nameEn: "Alexandria", nameAr: "الاسكندريه" },
	{ nameEn: "Assuit", nameAr: "اسيوط" },
	{ nameEn: "Aswan", nameAr: "اسوان" },
	{ nameEn: "Bani Suif", nameAr: "بني سويف" },
	{ nameEn: "Behira", nameAr: "البحيره" },
	{ nameEn: "Cairo", nameAr: "القاهره" },
	{ nameEn: "Cairo and Giza Outskirts", nameAr: "أطراف القاهرة والجيزة" },
	{ nameEn: "Dakahlia", nameAr: "الدقهليه" },
	{ nameEn: "Damietta", nameAr: "دمياط" },
	{ nameEn: "El Kalioubia", nameAr: "القليوبيه" },
	{ nameEn: "Fayoum", nameAr: "الفيوم" },
	{ nameEn: "Gharbia", nameAr: "الغربيه" },
	{ nameEn: "Giza", nameAr: "الجيزه" },
	{ nameEn: "Ismailia", nameAr: "الاسماعيليه" },
	{ nameEn: "Kafr Alsheikh", nameAr: "كفر الشيخ" },
	{ nameEn: "Luxor", nameAr: "الاقصر" },
	{ nameEn: "Menya", nameAr: "المنيا" },
	{ nameEn: "Monufia", nameAr: "المنوفيه" },
	{ nameEn: "New Valley", nameAr: "الوادي الجديد" },
	{ nameEn: "North Coast", nameAr: "الساحل الشمالي" },
	{ nameEn: "North Sinai", nameAr: "شمال سيناء" },
	{ nameEn: "Matrouh", nameAr: "مرسي مطروح", aliases: ['مطروح'] },
	{ nameEn: "Port Said", nameAr: "بور سعيد", aliases: ["بورسعيد"] },
	{ nameEn: "Qena", nameAr: "قنا" },
	{ nameEn: "Red Sea", nameAr: "البحر الاحمر" },
	{ nameEn: "Sharqia", nameAr: "الشرقيه" },
	{ nameEn: "Sohag", nameAr: "سوهاج" },
	{ nameEn: "South Sinai", nameAr: "جنوب سيناء" },
	{ nameEn: "Suez", nameAr: "السويس" }
];
