// shipping-company.dto.ts
// --- File: backend/src/shipping/shipping.dto.ts ---
import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsEnum, IsNumber, IsObject, IsOptional, IsString, MinLength, ValidateNested } from 'class-validator';
import { UnifiedShippingStatus } from 'entities/shipping.entity';
import { i18nValidationMessage } from "nestjs-i18n";



export class SetActiveDto {
    @IsBoolean({message: i18nValidationMessage('validation.is_boolean')})
    isActive: boolean;
}

export class SetProviderCredentialsDto {
    @IsObject({message: i18nValidationMessage('validation.is_object')})
    credentials: {
        apiKey?: string;

        // optional (not required in current integration)
        accountId?: string;

        // webhook security (optional but recommended)
        webhookHeaderName?: string; // default "Authorization"
        webhookSecret?: string;     // generated by backend if missing
    };
}

export class CreateShipmentDto {
    @IsOptional()
    @IsString({message: i18nValidationMessage('validation.is_string')})
    notes?: string;

    @IsOptional()
    weightKg?: number;

    @IsOptional()
    @IsEnum(['Small', 'Medium', 'Large'],{ message: (args) => { return i18nValidationMessage('validation.is_enum')({...args, constraints: [Object.values(['Small', 'Medium', 'Large']).join(', ')], }); }})
    size?: 'Small' | 'Medium' | 'Large';
}

export class AssignOrderDto extends CreateShipmentDto { }

export class ManualUpdateShipmentStatusDto {
    @IsEnum(UnifiedShippingStatus,{ message: (args) => { return i18nValidationMessage('validation.is_enum')({...args, constraints: [Object.values(UnifiedShippingStatus).join(', ')], }); }})
    status!: UnifiedShippingStatus;
}

export class BulkAssignItemDto extends CreateShipmentDto {
    @IsString({message: i18nValidationMessage('validation.is_string')})
    orderId: string;
}

export class BulkAssignOrderDto {
    @IsArray({message: i18nValidationMessage('validation.is_array')})
    @ValidateNested({ each: true })
    @Type(() => BulkAssignItemDto)
    items: BulkAssignItemDto[];
}

export class PrintMassAWBDto {
    @IsArray({message: i18nValidationMessage('validation.is_array')})
    @IsString({ each: true })
    orderIds: string[];

    @IsOptional()
    @IsEnum(['A4', 'A6'],{ message: (args) => { return i18nValidationMessage('validation.is_enum')({...args, constraints: [Object.values(['A4', 'A6']).join(', ')], }); }})
    requestedAwbType?: 'A4' | 'A6' = 'A4';

    @IsOptional()
    @IsEnum(['ar', 'en'],{ message: (args) => { return i18nValidationMessage('validation.is_enum')({...args, constraints: [Object.values(['ar', 'en']).join(', ')], }); }})
    lang?: 'ar' | 'en' = 'ar';
}

export class CreateShippingCompanyDto {
    @IsString({message: i18nValidationMessage('validation.is_string')})
    @MinLength(2, { message: i18nValidationMessage('validation.min_length') })
    name: string;

    @IsBoolean({message: i18nValidationMessage('validation.is_boolean')})
    @IsOptional()
    isActive?: boolean;
}

export class UpdateShippingCompanyDto extends CreateShippingCompanyDto { }